//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Body { get; set; }
        public System.DateTime DatePublished { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public System.Guid authorId { get; set; }
        public System.Guid CategoryId { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
